import { Controller, Get, Parameter } from "@antelopejs/interface-api";
import { GetModel } from "@antelopejs/interface-database-decorators";
import { AuthOwnerOnly, AuthRawUser } from "@antelopejs/interface-dms/auth";
import type { User } from "@antelopejs/interface-dms/auth/db";
import {
  RequestLogModel,
  RouteModel,
  type RouteModel as RouteModelType,
  RouteStatisticsModel,
  type RouteStatisticsModel as RouteStatisticsModelType,
} from "@/db";
import { parsePeriodDays, resolvePeriodDays } from "@/services/period";
import { queryRequestLogsScoped } from "@/services/request-log/read";
import { getScopedRouteKeys } from "@/services/scope";
import { getActiveScope } from "@/services/settings";
import {
  getRequestHistory,
  getStatusBreakdown,
  getSummaryKpis,
  getWatchList,
} from "@/services/statistics-aggregate";
import {
  CRITICAL_ERROR_RATE,
  DEGRADED_SLOW_ROUTES,
  ELEVATED_ERROR_RATE,
} from "@/types";

const DEFAULT_HISTORY_DAYS = 7;
const ACTIVITY_LIMIT = 10;
const WATCH_LIMIT = 4;

@AuthOwnerOnly()
export class SummaryController extends Controller("/api/monitoring/summary") {
  @Get("")
  async getSummary(@AuthRawUser() _user: User) {
    const [routes, stats] = models();
    const keys = await getScopedRouteKeys(routes, getActiveScope());
    const total = await countScopedRoutes(routes, keys);
    const kpis = await getSummaryKpis(stats, total, keys);
    return {
      kpis,
      autoGeneratedCount: 0,
      customCount: total,
    };
  }

  @Get("health")
  async getHealth(@AuthRawUser() _user: User) {
    const [routes, stats] = models();
    const keys = await getScopedRouteKeys(routes, getActiveScope());
    const total = await countScopedRoutes(routes, keys);
    const kpis = await getSummaryKpis(stats, total, keys);
    const errorRate =
      kpis.callsToday > 0 ? kpis.errors24h / kpis.callsToday : 0;
    const lastIncident = await findLastIncident(keys);
    return {
      status: pickStatus(errorRate, kpis.slowRoutesCount),
      errorRate,
      averageLatencyMs: kpis.averageLatencyMs,
      uptime: null,
      lastIncidentAt: lastIncident?.timestamp ?? null,
    };
  }

  @Get("history")
  async getHistory(
    @AuthRawUser() _user: User,
    @Parameter("period", "query") period?: string,
  ) {
    const days = resolvePeriodDays(period, DEFAULT_HISTORY_DAYS);
    const keys = await getScopedRouteKeys(
      GetModel(RouteModel),
      getActiveScope(),
    );
    return getRequestHistory(GetModel(RouteStatisticsModel), days, keys);
  }

  @Get("status-breakdown")
  async getStatusBreakdown(
    @AuthRawUser() _user: User,
    @Parameter("period", "query") period?: string,
  ) {
    const days = parsePeriodDays(period);
    const keys = await getScopedRouteKeys(
      GetModel(RouteModel),
      getActiveScope(),
    );
    return getStatusBreakdown(GetModel(RouteStatisticsModel), days, keys);
  }

  @Get("watch-list")
  async getWatchList(
    @AuthRawUser() _user: User,
    @Parameter("limit", "query") limit?: string,
  ) {
    const lim = clampInt(limit, 1, 20, WATCH_LIMIT);
    const keys = await getScopedRouteKeys(
      GetModel(RouteModel),
      getActiveScope(),
    );
    return getWatchList(GetModel(RouteStatisticsModel), lim, keys);
  }

  @Get("activity")
  async getActivity(@AuthRawUser() _user: User) {
    const routesModel = GetModel(RouteModel);
    const keys = await getScopedRouteKeys(routesModel, getActiveScope());
    const errorPage = await queryRequestLogsScoped(
      GetModel(RequestLogModel),
      {
        statusClass: "server-error",
        limit: ACTIVITY_LIMIT,
      },
      keys,
    );
    const routes = await routesModel.getAll();
    const recentRoutes = routes
      .filter((r) => !keys || keys.has(`${r.method.toUpperCase()}:${r.uri}`))
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
      .slice(0, ACTIVITY_LIMIT)
      .map((r) => ({
        kind: "route-created" as const,
        timestamp: r.createdAt,
        method: r.method,
        uri: r.uri,
      }));
    const errors = errorPage.results.map((l) => ({
      kind: "error" as const,
      timestamp: l.timestamp,
      method: l.method,
      uri: l.uri,
      statusCode: l.statusCode,
    }));
    return [...recentRoutes, ...errors]
      .sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime())
      .slice(0, ACTIVITY_LIMIT);
  }
}

function models(): [RouteModelType, RouteStatisticsModelType] {
  return [GetModel(RouteModel), GetModel(RouteStatisticsModel)];
}

/** Scoped route count: size of the key set, or every synced route for "all". */
async function countScopedRoutes(
  routes: RouteModelType,
  keys: Set<string> | null,
): Promise<number> {
  if (keys) return keys.size;
  return routes.table.count().run();
}

async function findLastIncident(keys: Set<string> | null) {
  const page = await queryRequestLogsScoped(
    GetModel(RequestLogModel),
    {
      statusClass: "server-error",
      limit: 1,
    },
    keys,
  );
  return page.results[0];
}

function pickStatus(
  errorRate: number,
  slowCount: number,
): "healthy" | "degraded" | "down" {
  if (errorRate > CRITICAL_ERROR_RATE) return "down";
  if (errorRate > ELEVATED_ERROR_RATE || slowCount > DEGRADED_SLOW_ROUTES) {
    return "degraded";
  }
  return "healthy";
}

function clampInt(
  raw: string | undefined,
  min: number,
  max: number,
  fallback: number,
): number {
  if (!raw) return fallback;
  const n = parseInt(raw, 10);
  if (Number.isNaN(n)) return fallback;
  return Math.max(min, Math.min(max, n));
}
