/**
 * Frontend introspection facade.
 *
 * Single composable wrapping every /api/monitoring/* fetch the new pages need.
 * Mirrors the backend's `src/services/introspection` swap-point: when
 * the runtime gains real introspection and endpoint shapes change,
 * only this file needs updating.
 */

// --- Shapes mirrored from the backend ---------------------------------------

export type ParameterSource =
  | 'body'
  | 'query'
  | 'param'
  | 'header'
  | 'context'
  | 'result'
  | 'raw'
  | 'stream'
  | 'connection'
  | 'unknown'

export type InferredType =
  | 'string'
  | 'number'
  | 'boolean'
  | 'object'
  | 'buffer'
  | 'stream'
  | 'unknown'

export interface ParameterInfo {
  index: number
  name: string | null
  source: ParameterSource
  multi: boolean
  inferredType: InferredType
  modifierCount: number
  rawProviderSource?: string
  hint?: string
}

export interface PropertyInfo {
  key: string
  decorator: string
  modifierCount: number
  rawProviderSource?: string
  hint?: string
}

export type MiddlewareMode = 'prefix' | 'postfix' | 'monitor'

export interface MiddlewareInfo {
  id: string
  mode: MiddlewareMode
  location: string
  method: string
  callbackName: string
  priority?: number
  isAuth: boolean
}

export interface InferredErrorCode {
  status: number
  reason: string | null
  source: 'assert' | 'HTTPResult'
}

export type RouteHandlerMode =
  | 'handler'
  | 'prefix'
  | 'postfix'
  | 'monitor'
  | 'websocket'

export interface RouteInspection {
  id: string
  location: string
  method: string
  mode: RouteHandlerMode
  callbackName: string
  priority?: number
  parameters: ParameterInfo[]
  properties: PropertyInfo[]
  applicableMiddleware: MiddlewareInfo[]
  errorCodes: InferredErrorCode[]
}

export interface RouteDocPayload extends RouteInspection {
  registeredAt: string | null
  updatedAt: string | null
}

export interface FolderInspection {
  path: string
  middlewareAtOrAbove: MiddlewareInfo[]
  routes: RouteInspection[]
}

export interface TreeNodeStats {
  requestsCount: number
  errorRate: number
  slow: boolean
}

export interface ApiTreeNode {
  label: string
  value?: string
  icon?: string
  expandable?: boolean
  selectable?: boolean
  children?: ApiTreeNode[]
  customData?: TreeNodeStats
}

export interface ChartDataPoint {
  x: string
  y: number
  label?: string
  category?: string
}

export interface ChartResponse {
  data?: ChartDataPoint[]
}

export interface RouteAggregate {
  routeKey: string
  method: string
  uri: string
  requestsCount: number
  averageLatencyMs: number
  minLatencyMs: number
  maxLatencyMs: number
  errorsClient: number
  errorsServer: number
  errorRate: number
}

export interface RequestLogSummary {
  _id: string
  timestamp: string
  method: string
  uri: string
  rawPath: string
  routeId?: string
  statusCode: number
  responseTimeMs: number
  ip?: string
  userAgent?: string
}

export interface RouteStatsPayload {
  route: { id: string; location: string; method: string }
  aggregate?: RouteAggregate
  charts: {
    counts: ChartResponse
    latency: ChartResponse
  }
  recent: RequestLogSummary[]
}

export interface SummaryKpis {
  totalRoutes: number
  routesWithErrors24h: number
  slowRoutesCount: number
  averageLatencyMs: number
  callsToday: number
  errors24h: number
}

export interface SummaryPayload {
  kpis: SummaryKpis
  autoGeneratedCount: number
  customCount: number
}

export interface HistoryPoint {
  day: number
  label: string
  success: number
  clientErrors: number
  serverErrors: number
  slow: number
}

export interface StatusBreakdown {
  success: number
  clientErrors: number
  serverErrors: number
  total: number
}

export type WatchListFlag = 'broken' | 'slow' | 'warn'

export interface WatchListItem {
  routeKey: string
  method: string
  uri: string
  errorRate: number
  averageLatencyMs: number
  requestsLast24h: number
  flag: WatchListFlag
}

export type ActivityKind = 'route-created' | 'error'

export interface ActivityItem {
  kind: ActivityKind
  timestamp: string
  method: string
  uri: string
  statusCode?: number
}

export interface MonitoringPayload {
  period: { granularity: 'minute' | 'hour' | 'day'; count: number }
  kpis: SummaryKpis
  history: HistoryPoint[]
  slowest: RouteAggregate[]
  mostErroring: RouteAggregate[]
  recent: RequestLogSummary[]
}

export interface MonitoringFilters {
  period?: string
  route?: string
}

export type LogTab = 'requests' | 'errors' | 'slow'

export interface LogFilters {
  tab?: LogTab
  period?: string
  method?: string
  status?: string
  search?: string
  cursor?: string
  limit?: number
}

export interface LogPage {
  results: RequestLogSummary[]
  nextCursor: string | null
}

// Full single-log shape from /api/monitoring/logs/:id — same body as the
// LogDetailDrawer prop. Defined here so both Logs page and StatsView
// can fetch through the same facade.
export interface FullRequestLog extends RequestLogSummary {
  pathParams?: Record<string, string>
  query?: Record<string, string | string[]>
  requestHeaders?: Record<string, string>
  requestBody?: string
  requestBodyTruncated?: boolean
  responseHeaders?: Record<string, string>
  responseBody?: string
  responseBodyTruncated?: boolean
  error?: { message: string; stack?: string }
}

/**
 * How far back each store reaches, per the configured retentions. The day
 * rollups behind the Overview and Routes charts and the raw logs behind the
 * Logs page are pruned by two different settings.
 *
 * `requestLogRetentionDays` is optional: a backend older than the field simply
 * omits it, and callers fall back to the statistics one.
 */
export interface StatsRetention {
  statisticsLifetimeDays: number
  requestLogRetentionDays?: number
}

// --- Facade -----------------------------------------------------------------

export function useApiIntrospection() {
  const { $authFetch } = useAuthFetch()

  return {
    // Tree
    getTree: (period?: string) =>
      $authFetch<ApiTreeNode[]>(
        `/api/monitoring/routes/tree${period ? `?period=${encodeURIComponent(period)}` : ''}`,
      ),

    // Per-route tabs
    getRouteDoc: (id: string) =>
      $authFetch<RouteDocPayload>(`/api/monitoring/routes/route/${id}/doc`),
    getRouteConfig: (id: string) =>
      $authFetch<RouteInspection>(`/api/monitoring/routes/route/${id}/config`),
    getRouteStats: (id: string, period = '7d') =>
      $authFetch<RouteStatsPayload>(
        `/api/monitoring/routes/route/${id}/stats?period=${encodeURIComponent(period)}`,
      ),

    // Retention backing the period selectors
    getRetention: () =>
      $authFetch<StatsRetention>('/api/monitoring/settings/retention'),

    // Summary page
    getSummary: () => $authFetch<SummaryPayload>('/api/monitoring/summary'),
    getSummaryHistory: (period = '7d') =>
      $authFetch<HistoryPoint[]>(
        `/api/monitoring/summary/history?period=${encodeURIComponent(period)}`,
      ),
    getStatusBreakdown: (period = '7d') =>
      $authFetch<StatusBreakdown>(
        `/api/monitoring/summary/status-breakdown?period=${encodeURIComponent(period)}`,
      ),
    getWatchList: (limit = 4) =>
      $authFetch<WatchListItem[]>(
        `/api/monitoring/summary/watch-list?limit=${limit}`,
      ),
    getActivity: () => $authFetch<ActivityItem[]>('/api/monitoring/summary/activity'),

    // Monitoring page
    getMonitoring: (filters: MonitoringFilters = {}) => {
      const params = new URLSearchParams()
      params.set('period', filters.period ?? '7d')
      if (filters.route) params.set('route', filters.route)
      return $authFetch<MonitoringPayload>(
        `/api/monitoring/metrics?${params.toString()}`,
      )
    },

    // Logs page
    getLogs: (filters: LogFilters = {}) => {
      const params = new URLSearchParams()
      if (filters.tab) params.set('tab', filters.tab)
      if (filters.period) params.set('period', filters.period)
      if (filters.method) params.set('method', filters.method)
      if (filters.status) params.set('status', filters.status)
      if (filters.search) params.set('search', filters.search)
      if (filters.cursor) params.set('cursor', filters.cursor)
      if (filters.limit) params.set('limit', String(filters.limit))
      const qs = params.toString()
      return $authFetch<LogPage>(`/api/monitoring/logs${qs ? `?${qs}` : ''}`)
    },
    getLog: (id: string) =>
      $authFetch<FullRequestLog>(`/api/monitoring/logs/${id}`),
  }
}
